### PR TITLE
React: Fix 'Pipeline: undefined undefined' issue in analysis dialogs

### LINKED ISSUE #215: Post-migration, analysis dialog shows Pipeline: undefined undefined

### PR DESCRIPTION
**Pull request by frewmack**
Closes #215

Also fixes a bug where DetailSection fields can overlap the Edit Mode switch if the field is long enough.

### CODE REVIEW

File: react/src/pages/datasets/DatasetTable.tsx [hunk 1]
```diff
@@ -103,11 +103,15 @@ export default function DatasetTable() {
...
                         setDatasets(
-                            datasets.map(dataset =>
-                                dataset.dataset_id === dataset_id
-                                    ? { ...dataset, ...newDataset }
-                                    : dataset
-                            )
+                            datasets.map(dataset => {
+                                if (dataset.dataset_id === dataset_id) {
+                                    const updatedDataset = { ...dataset, ...newDataset };
+                                    setInfoDataset(updatedDataset);
```
Comment (kevinlul) [inline react/src/pages/datasets/DatasetTable.tsx:109]: If I'm understanding right, this is because the dialog edits call onUpdate and this state is passed as a prop all the way down?

**Review by kevinlul — COMMENTED** [review]
The gap to fix the overlapping bug looks pretty bad but given how the components are structured I don't know if we can move the switch into the dialog titlebar.

File: react/src/pages/datasets/DatasetTable.tsx (hunk 1 above)
Comment (frewmack) [reply react/src/pages/datasets/DatasetTable.tsx:109]: Yep. The 'info dataset' has to be updated or else the contents of the dialog will not update post-edit.

**Comment by frewmack** [comment]
> 
> 
> The gap to fix the overlapping bug looks pretty bad but given how the components are structured I don't know if we can move the switch into the dialog titlebar.

Another option could be to keep the switch in its original position, but place it inside a Grid that extends to the bottom of the section. I'll try that instead to see how it looks.

**Review by kevinlul — APPROVED** [review]
LGTM
