### PR TITLE
React: Fix notes changing table row height

### LINKED ISSUE #231: Investigate handling longer notes in tables
Variable row height can be jarring when flipping between pages

### PR DESCRIPTION
**Pull request by frewmack**
Closes #231 
The component handles overflowing text in `notes` columns, and expands on mouse hover to show the entire entry.

### CODE REVIEW

File: react/src/pages/utils/components/Note.tsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+const useStyles = makeStyles(theme => ({
+    notes: {
+        // TODO: Find a better way to set maxWidth using container width
+        maxWidth: "16em",
+        whiteSpace: "nowrap",
+        overflow: "hidden",
+        textOverflow: "ellipsis",
+        "&:hover": {
+            whiteSpace: "normal",
+            textOverflow: "default",
```
Comment (kevinlul) [inline react/src/pages/utils/components/Note.tsx:13]: default isn't a style. You can use initial or inherit

**Review by kevinlul — CHANGES_REQUESTED** [review]
This can cause some weird reflows on hover. I believe it's because there's no minimum width set but having one might just change this weird reflow point instead of fixing the problem.

Screen Shot 2020-11-30 at 09 25 39

Screen Shot 2020-11-30 at 09 25 52

**Review by kevinlul — APPROVED** [review]
LGTM
